### PR TITLE
removes economic disadvantage info from leaking

### PR DESCRIPTION
**Pull request by esotrope**
Same changes to remove economic disadvantage from reporting except this is branched from develop and to be merged to develop

### CODE REVIEW

**Comment by malaffoon** [comment]
Is this the same git change set?

**Comment by esotrope** [comment]
@malaffoon - no, did it fresh to avoid collisions before they happen

**Comment by malaffoon** [comment]
Hmm, that's going to make a future merge to master painful.

**Comment by esotrope** [comment]
@malaffoon : / painful in what way? there will be bigger pains when merging develop onto master after all that refactoring no?

**Comment by esotrope** [comment]
hotfix merged with develop - closing PR

**Pull request closed without merging**
