### PR TITLE
improves value formatting on percentile tables

### PR DESCRIPTION
**Pull request by esotrope**
Before:

image

After:

image

### CODE REVIEW

**Comment by esotrope** [comment]
scratch the date format change. This will blow it up

image

**Comment by agorina** [comment]
Looks much better!

**Comment by agorina** [comment]
But..but..don't you still need a year?

**Comment by malaffoon** [comment]
i like the date format change. For the table with lots of columns will it just wrap the effective dates column making it two lines? That would be okay for now i think.

**Comment by esotrope** [comment]
Actually tried it out and it fits:
image

should have done that before reverting : j

**Pull request merged**
