### PR TITLE
DWR-466 Remove invalid prompts from group results page when viewing "…

### PR DESCRIPTION
**Pull request by wtritch**
…Most recent" assessment

### CODE REVIEW

**Comment by wtritch** [comment]
This PR hides the "Click an item to remove it from the list" prompt text and "X" icon on assessments when viewing the most recent.

**Comment by esotrope** [comment]
Is this the requirement? I could also imagine them maybe wanting to allow removing it and then auto switch the user to the custom tab if they change anything.

**Comment by wtritch** [comment]
This was the suggested fix per the jira, and it's logically complete.  I could see arguments either way, but this seems small and changeable enough that I didn't want to delay development to hold a meeting over it.

**Comment by esotrope** [comment]
Sounds good 👍  Just wanted to make sure it wasn't just what we thought was best but was also what sbac wanted.

**Pull request merged**
