### PR TITLE
table changes in primeng-overrides.less

### PR DESCRIPTION
**Pull request by aaronsleeper**
when i merged it got a bunch of changes from develop. all i need to put into dev is the updated table styles to fix 605

### CODE REVIEW

**Comment by esotrope** [comment]
It looks like the PR was made in reverse, It looks like you are merging develop onto your branch instead of the other way. Try making a new PR with develop as the target branch, and your branch as the source

**Comment by wtritch** [comment]
Go ahead and merge into your branch.  I'll be happy to review the PR to merge your branch back into develop, but I'm not reviewing a 93-file PR =P

**Comment by bgsavage** [comment]
I think you created a PR in the wrong direction.  While you definitely want to merge develop into your branch, you don't need to create a PR for it.  You do need to create a PR to merge your branch back into develop.

**Comment by bgsavage** [comment]
Sorry for the race condition in the comments :D

**Comment by esotrope** [comment]
It was a race and my thread won : D

**Pull request merged**
